<?php

namespace Yakamara\Roadie\Console;

use RecursiveCallbackFilterIterator;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use rex_addon;
use rex_console_command;
use rex_file;
use rex_path;
use SplFileInfo;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

use function count;
use function dirname;
use function in_array;

use const GLOB_ONLYDIR;
use const PATHINFO_EXTENSION;

class GenerateComponentImportsCommand extends rex_console_command
{
    protected function configure(): void
    {
        $this->setDescription('Generates the component imports file for the webpack build');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $root = rex_path::base();
        $outputPath = $root . 'assets/roadie-component-imports.js';
        $componentDir = rex_addon::get('roadie')->getPath('lib/Component');
        $registryFile = rex_addon::get('roadie')->getPath('src/scripts/core/ComponentRegistry.js');
        $waComponentsDir = $root . 'node_modules/@awesome.me/webawesome/dist/components';
        $projectComponentsDir = $root . 'assets/scripts/components';

        $scanDirs = [
            rex_path::src('templates'),
            rex_path::src('modules'),
            rex_addon::get('project')->getPath(),
            $projectComponentsDir,
        ];

        if (!is_dir($waComponentsDir)) {
            $output->writeln('<error>WebAwesome dist/components nicht gefunden. Bitte npm install ausführen.</error>');
            return self::FAILURE;
        }

        $availableWa = array_flip(array_filter(
            scandir($waComponentsDir),
            static fn ($d) => '.' !== $d && '..' !== $d && is_dir($waComponentsDir . '/' . $d),
        ));

        // Alle Verzeichnisse scannen
        $allWaTags = [];
        $allComponentFolders = [];
        $usesYform = false;

        foreach ($scanDirs as $dir) {
            ['waTags' => $waTags, 'componentFolders' => $componentFolders, 'usesYform' => $yform] = $this->scanDir($dir, $componentDir);
            foreach ($waTags as $tag => $_) {
                $allWaTags[$tag] = true;
            }
            foreach ($componentFolders as $folder => $_) {
                $allComponentFolders[$folder] = true;
            }
            if ($yform) {
                $usesYform = true;
            }
        }

        // YForm-Templates scannen, wenn Formulare genutzt werden
        if ($usesYform) {
            $ytemplateDirs = glob(rex_path::src('addons/*/ytemplates/roadie'), GLOB_ONLYDIR) ?: [];
            foreach ($ytemplateDirs as $dir) {
                ['waTags' => $waTags, 'componentFolders' => $componentFolders] = $this->scanDir($dir, $componentDir);
                foreach ($waTags as $tag => $_) {
                    $allWaTags[$tag] = true;
                }
                foreach ($componentFolders as $folder => $_) {
                    $allComponentFolders[$folder] = true;
                }
            }
        }

        ksort($allWaTags);
        ksort($allComponentFolders);

        $lines = [
            '// Auto-generated by roadie:generate-component-imports — do not edit manually',
            '',
        ];

        // WA-Komponenten
        $waImported = [];
        $waSkipped = [];

        foreach (array_keys($allWaTags) as $tag) {
            $name = substr($tag, 3); // 'wa-' entfernen
            if (isset($availableWa[$name])) {
                $waImported[] = $tag;
                $lines[] = "import '@awesome.me/webawesome/dist/components/{$name}/{$name}.js';";
            } else {
                $waSkipped[] = $tag;
            }
        }

        // Roadie-Komponenten-Assets
        $registrations = [];
        $scssImports = [];
        $assetImports = [];

        foreach (array_keys($allComponentFolders) as $folderName) {
            $scriptsDir = "{$componentDir}/{$folderName}/scripts";
            $stylesDir = "{$componentDir}/{$folderName}/styles";
            $assetsDir = "{$componentDir}/{$folderName}/assets";
            $mainScript = "{$scriptsDir}/{$folderName}.js";

            $hasMainScript = file_exists($mainScript);
            $hasStyles = is_dir($stylesDir);

            if ($hasMainScript || $hasStyles) {
                if ($hasStyles) {
                    $scssFiles = array_filter(scandir($stylesDir), static fn ($f) => str_ends_with($f, '.scss'));
                    sort($scssFiles);
                    foreach ($scssFiles as $file) {
                        $scssImports[] = $this->relImport($outputPath, "{$stylesDir}/{$file}");
                    }
                }
                if ($hasMainScript) {
                    $registrations[] = ['className' => $folderName, 'scriptFile' => $mainScript];
                }
            } elseif (is_dir($assetsDir)) {
                $assetFiles = array_filter(
                    scandir($assetsDir),
                    static fn ($f) => in_array(pathinfo($f, PATHINFO_EXTENSION), ['js', 'css'], true),
                );
                sort($assetFiles);
                foreach ($assetFiles as $file) {
                    $assetImports[] = $this->relImport($outputPath, "{$assetsDir}/{$file}");
                }
            }
        }

        if ($scssImports) {
            $lines[] = '';
            foreach ($scssImports as $imp) {
                $lines[] = "import '{$imp}';";
            }
        }

        if ($assetImports) {
            $lines[] = '';
            foreach ($assetImports as $imp) {
                $lines[] = "import '{$imp}';";
            }
        }

        // Projektspezifische Komponenten
        foreach ($this->findProjectComponents($projectComponentsDir) as $entry) {
            $registrations[] = $entry;
        }

        if ($registrations) {
            $lines[] = '';
            $lines[] = "import { register, setupDelegation, initAll, observeDOM } from '{$this->relImport($outputPath, $registryFile)}';";
            foreach ($registrations as ['className' => $className, 'scriptFile' => $scriptFile]) {
                $lines[] = "import {$className} from '{$this->relImport($outputPath, $scriptFile)}';";
            }
            $lines[] = '';
            foreach ($registrations as ['className' => $className]) {
                $lines[] = "register({$className});";
            }
            $lines[] = '';
            $lines[] = 'function boot() {';
            $lines[] = '    setupDelegation();';
            $lines[] = '    initAll();';
            $lines[] = '    observeDOM();';
            $lines[] = '}';
            $lines[] = '';
            $lines[] = "if (document.readyState === 'loading') {";
            $lines[] = "    document.addEventListener('DOMContentLoaded', boot);";
            $lines[] = '} else {';
            $lines[] = '    boot();';
            $lines[] = '}';
        }

        $lines[] = '';
        rex_file::put($outputPath, implode("\n", $lines));

        $output->writeln('<info>Generated ' . $outputPath . '</info>');
        if ($usesYform) {
            $output->writeln('  YForm templates: scanned (' . count($ytemplateDirs) . ' dir(s))');
        }
        $output->writeln('  WA (' . count($waImported) . '): ' . (implode(', ', $waImported) ?: '—'));
        if ($waSkipped) {
            $output->writeln('<comment>  Skipped WA (not in package): ' . implode(', ', $waSkipped) . '</comment>');
        }
        $output->writeln('  Registered (' . count($registrations) . '): ' . (implode(', ', array_column($registrations, 'className')) ?: '—'));
        $output->writeln('  SCSS (' . count($scssImports) . '): ' . (implode(', ', array_map('basename', $scssImports)) ?: '—'));
        if ($assetImports) {
            $output->writeln('  Assets fallback (' . count($assetImports) . '): ' . implode(', ', array_map('basename', $assetImports)));
        }

        return self::SUCCESS;
    }

    // ── Scanning ───────────────────────────────────────────────────────────────

    private function scanDir(string $dir, string $componentDir): array
    {
        $waTags = [];
        $componentFolders = [];
        $usesYform = false;

        if (!is_dir($dir)) {
            return ['waTags' => $waTags, 'componentFolders' => $componentFolders, 'usesYform' => $usesYform];
        }

        $iterator = new RecursiveIteratorIterator(
            new RecursiveCallbackFilterIterator(
                new RecursiveDirectoryIterator($dir, RecursiveDirectoryIterator::SKIP_DOTS),
                static fn (SplFileInfo $f) => !$f->isDir() || !in_array($f->getFilename(), ['node_modules', 'vendor'], true),
            ),
        );

        foreach ($iterator as $file) {
            if (!in_array($file->getExtension(), ['php', 'html', 'twig', 'js'], true)) {
                continue;
            }

            $content = file_get_contents($file->getPathname());

            // Direkte wa-*-Tags
            if (preg_match_all('/<(wa-[a-z][a-z0-9-]*)/', $content, $m)) {
                foreach ($m[1] as $tag) {
                    $waTags[$tag] = true;
                }
            }

            if ('php' === $file->getExtension()) {
                // YForm-Nutzung erkennen
                if (str_contains($content, 'rex_yform')) {
                    $usesYform = true;
                }

                // PHP-use-Statements → Roadie-Komponenten
                if (preg_match_all('/use\s+Yakamara\\\\Roadie\\\\Component\\\\([A-Za-z\\\\]+)\s*;/', $content, $useMatches)) {
                    foreach ($useMatches[1] as $classPath) {
                        $parts = explode('\\', $classPath);
                        if (count($parts) < 2) {
                            continue;
                        }

                        $subfolder = $parts[count($parts) - 2];
                        $className = $parts[count($parts) - 1];
                        $componentFolders[$subfolder] = true;

                        $tplPath = "{$componentDir}/{$subfolder}/templates/{$className}.php";
                        if (!file_exists($tplPath)) {
                            continue;
                        }

                        if (preg_match_all('/<(wa-[a-z][a-z0-9-]*)/', file_get_contents($tplPath), $tplMatches)) {
                            foreach ($tplMatches[1] as $tag) {
                                $waTags[$tag] = true;
                            }
                        }
                    }
                }
            }
        }

        return ['waTags' => $waTags, 'componentFolders' => $componentFolders, 'usesYform' => $usesYform];
    }

    private function findProjectComponents(string $dir): array
    {
        $results = [];
        if (!is_dir($dir)) {
            return $results;
        }

        $files = array_filter(scandir($dir), static fn ($f) => str_ends_with($f, '.js') && 'index.js' !== $f);
        sort($files);

        foreach ($files as $file) {
            $content = file_get_contents("{$dir}/{$file}");
            if (!str_contains($content, 'static componentName') || !str_contains($content, 'export default class')) {
                continue;
            }
            if (preg_match('/export default class (\w+)/', $content, $m)) {
                $results[] = ['className' => $m[1], 'scriptFile' => "{$dir}/{$file}"];
            }
        }

        return $results;
    }

    // ── Helpers ────────────────────────────────────────────────────────────────

    private function relImport(string $outputFile, string $targetFile): string
    {
        $rel = self::relativePath(dirname($outputFile), $targetFile);
        return str_starts_with($rel, '.') ? $rel : './' . $rel;
    }

    private static function relativePath(string $from, string $to): string
    {
        $from = array_values(array_filter(explode('/', str_replace('\\', '/', $from))));
        $to = array_values(array_filter(explode('/', str_replace('\\', '/', $to))));

        while (count($from) && count($to) && $from[0] === $to[0]) {
            array_shift($from);
            array_shift($to);
        }

        return str_repeat('../', count($from)) . implode('/', $to);
    }
}
